
title = "QA Discovery"
author = "Nao"
copyright = "2015-2023 naodeng ｜ wechat: teststudents"
description = "A Quality Analyst, Not A Quality Assurance"
profilePicture = "https://avatars.githubusercontent.com/u/7599466?v=4"
keywords = ["naodeng", "dengnao","nao", "naodeng.tech","nao","API testing","performance testing","automation testing", "软件测试","自动化测试","敏捷测试"]
favicon = ""
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
googleSiteVerify = "google5e9a7c9479924ed2"
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
postSectionName = "blog"
relatedPosts = true
numberOfRelatedPosts = 4
contentratio = 0.8

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
serverURL = "naodeng-umami.vercel.app"
id = "b3b285c9-3c35-4398-9252-91bb70560b84"
trackerScriptName = "hugo.js"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/naodeng/"

[[socialIcons]]
icon = "fab fa-medium"
title = "medium"
url = "https://naodeng.medium.com/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:dengnao@gmail.com"

[mermaid]
# enable = true

[enableRobotsTXT]
enable = true