#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
from urllib.parse import quote_plus


def qurl_google(q: str) -> str:
    return f"https://www.google.com/search?q={quote_plus(q)}"


def qurl_wikipedia(q: str) -> str:
    return f"https://en.wikipedia.org/w/index.php?search={quote_plus(q)}"


def qurl_medium(q: str) -> str:
    return f"https://medium.com/search?q={quote_plus(q)}"


def qurl_qa(q: str) -> str:
    return f"https://www.google.com/search?q={quote_plus(q + ' software testing qa engineering')}"


def slots(title: str, n: int = 10) -> str:
    lines = []
    for i in range(1, n + 1):
        lines.append(f"{i}. 链接：")
        lines.append("   标题：")
        lines.append("   证据摘录：")
        lines.append("   可信度判断：高/中/低")
    return "\n".join(lines)


def build_doc(term: dict, order: int) -> str:
    zh = term["zh"]
    en = term["en"]
    slug = term["slug"]

    gq = f"{en} software testing"
    wq = en
    mq = en
    qq = en

    return f'''---
title: "{zh} ｜ {en}"
slug: "{slug}"
order: {order}
status: "research-draft"
---

# {zh} ｜ {en}

## 检索任务

- Google：10 条
- Wikipedia：10 条
- Medium：10 条
- QA 专业站点：10 条

## 检索入口

- Google: {qurl_google(gq)}
- Wikipedia: {qurl_wikipedia(wq)}
- Medium: {qurl_medium(mq)}
- QA 专业站点: {qurl_qa(qq)}

## Source Capture - Google (10)

{slots('Google')}

## Source Capture - Wikipedia (10)

{slots('Wikipedia')}

## Source Capture - Medium (10)

{slots('Medium')}

## Source Capture - QA Professional Sites (10)

{slots('QA Sites')}

## Synthesis（用于最终词条）

### 1) 标准化定义

### 2) 适用边界 / 非适用边界

### 3) 方法步骤

### 4) 输入 / 输出

### 5) 核心指标

### 6) 工具与工程实践

### 7) 常见误区与改进建议

### 8) 与现有 wiki 词条关联（slug）

### 9) 参考资料（按来源分组）

'''


def main():
    ap = argparse.ArgumentParser(description="Create per-term research workbooks")
    ap.add_argument("--terms", required=True, help="JSON file generated by extract_terms_from_plan.py")
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    terms_data = json.loads(Path(args.terms).read_text(encoding="utf-8"))
    terms = terms_data.get("terms", [])
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for idx, t in enumerate(terms, start=1):
        p = out_dir / f"{t['slug']}.md"
        p.write_text(build_doc(t, idx), encoding="utf-8")

    print(f"Created {len(terms)} workbooks in {out_dir}")


if __name__ == "__main__":
    main()
