// Generated by scripts/sync-qaskills-from-repo.mjs. Do not edit manually.
export type QASkillCatalogGroup = {
  key: string;
  title: { "zh-cn": string; en: string };
  slugs: string[];
  groups: Array<{ key: string; title: { "zh-cn": string; en: string }; slugs: string[] }>;
};

export const QA_SKILL_CATALOG: QASkillCatalogGroup[] = [
  {
    "key": "跨阶段工作流",
    "title": {
      "zh-cn": "跨阶段工作流",
      "en": "Cross-phase workflows"
    },
    "slugs": [],
    "groups": [
      {
        "key": "需求发现与分析",
        "title": {
          "zh-cn": "需求发现与分析",
          "en": "Discovery"
        },
        "slugs": [
          "discover-testing",
          "product-quality-perspective",
          "qa-quality-perspective",
          "ux-quality-perspective",
          "technical-quality-perspective"
        ]
      },
      {
        "key": "开发与迭代",
        "title": {
          "zh-cn": "开发与迭代",
          "en": "Development"
        },
        "slugs": [
          "daily-testing-workflow",
          "sprint-testing-workflow",
          "project-delivery-perspective"
        ]
      },
      {
        "key": "发布与综合",
        "title": {
          "zh-cn": "发布与综合",
          "en": "Release"
        },
        "slugs": [
          "release-testing-workflow",
          "multi-role-quality-synthesis"
        ]
      }
    ]
  },
  {
    "key": "core-qa-skills-基础质量能力",
    "title": {
      "zh-cn": "Core QA Skills — 基础质量能力",
      "en": "Core QA Skills — Quality foundation"
    },
    "slugs": [],
    "groups": [
      {
        "key": "需求发现与分析",
        "title": {
          "zh-cn": "需求发现与分析",
          "en": "Discovery and Requirements Analysis"
        },
        "slugs": [
          "requirements-analysis",
          "requirements-analysis-plus"
        ]
      },
      {
        "key": "方案设计与测试策略",
        "title": {
          "zh-cn": "方案设计与测试策略",
          "en": "Solution Design and Test Strategy"
        },
        "slugs": [
          "test-strategy",
          "test-strategy-plus",
          "test-strategy-review"
        ]
      },
      {
        "key": "测试设计与准备",
        "title": {
          "zh-cn": "测试设计与准备",
          "en": "Test Design and Preparation"
        },
        "slugs": [
          "test-case-writing",
          "testcase-writer-plus",
          "test-case-reviewer",
          "test-case-reviewer-plus"
        ]
      },
      {
        "key": "测试执行与分析",
        "title": {
          "zh-cn": "测试执行与分析",
          "en": "Test Execution and Analysis"
        },
        "slugs": [
          "functional-testing",
          "api-testing",
          "manual-testing",
          "mobile-testing",
          "accessibility-testing",
          "security-testing"
        ]
      },
      {
        "key": "发布-缺陷与报告",
        "title": {
          "zh-cn": "发布、缺陷与报告",
          "en": "Release, Defects, and Reporting"
        },
        "slugs": [
          "bug-reporting",
          "test-reporting",
          "test-report-review"
        ]
      }
    ]
  },
  {
    "key": "engineering-qa-skills-质量工程能力",
    "title": {
      "zh-cn": "Engineering QA Skills — 质量工程能力",
      "en": "Engineering QA Skills — Quality engineering"
    },
    "slugs": [],
    "groups": [
      {
        "key": "需求与质量左移",
        "title": {
          "zh-cn": "需求与质量左移",
          "en": "Requirements and Shift Left"
        },
        "slugs": [
          "acceptance-criteria-review",
          "requirement-gap-analysis",
          "quality-risk-analysis",
          "testability-analysis"
        ]
      },
      {
        "key": "开发与持续集成",
        "title": {
          "zh-cn": "开发与持续集成",
          "en": "Development and Continuous Integration"
        },
        "slugs": [
          "code-review",
          "change-impact-analysis",
          "pr-test-impact-analysis",
          "api-contract-testing",
          "automation-testing"
        ]
      },
      {
        "key": "测试数据与自动化实现",
        "title": {
          "zh-cn": "测试数据与自动化实现",
          "en": "Test Data and Automation Implementation"
        },
        "slugs": [
          "test-data-generation",
          "api-test-bruno",
          "api-test-postman",
          "api-test-pytest",
          "api-test-restassure",
          "api-test-supertest",
          "ui-test-selenium",
          "ui-test-playwright",
          "ui-test-testcafe",
          "ui-test-cypress",
          "ui-test-puppeteer",
          "ui-test-webdriverio"
        ]
      },
      {
        "key": "测试执行与回归智能",
        "title": {
          "zh-cn": "测试执行与回归智能",
          "en": "Test Execution and Regression Intelligence"
        },
        "slugs": [
          "flaky-test-analysis",
          "regression-scope-analysis",
          "regression-test-selection",
          "ai-assisted-testing"
        ]
      },
      {
        "key": "性能工程与容量决策",
        "title": {
          "zh-cn": "性能工程与容量决策",
          "en": "Performance Engineering and Capacity Decisions"
        },
        "slugs": [
          "performance-testing",
          "performance-test-k6",
          "performance-test-gatling",
          "performance-test-jmeter",
          "performance-workload-modeling",
          "performance-result-analysis",
          "performance-bottleneck-analysis",
          "performance-regression-analysis",
          "capacity-planning-analysis"
        ]
      },
      {
        "key": "复盘与持续改进",
        "title": {
          "zh-cn": "复盘与持续改进",
          "en": "Retrospective and Continuous Improvement"
        },
        "slugs": [
          "root-cause-analysis",
          "log-analysis"
        ]
      }
    ]
  },
  {
    "key": "production-quality-skills-生产质量能力",
    "title": {
      "zh-cn": "Production Quality Skills — 生产质量能力",
      "en": "Production Quality Skills — Production quality"
    },
    "slugs": [],
    "groups": [
      {
        "key": "发布与生产验证",
        "title": {
          "zh-cn": "发布与生产验证",
          "en": "Release and Production Verification"
        },
        "slugs": [
          "production-verification"
        ]
      },
      {
        "key": "生产运行与事故响应",
        "title": {
          "zh-cn": "生产运行与事故响应",
          "en": "Production Operations and Incident Response"
        },
        "slugs": [
          "production-incident-analysis",
          "distributed-trace-analysis",
          "metrics-anomaly-analysis"
        ]
      }
    ]
  },
  {
    "key": "ai-native-qa-skills-ai-原生质量能力",
    "title": {
      "zh-cn": "AI Native QA Skills — AI 原生质量能力",
      "en": "AI Native QA Skills — AI-native quality"
    },
    "slugs": [],
    "groups": [
      {
        "key": "ai-功能需求与风险",
        "title": {
          "zh-cn": "AI 功能需求与风险",
          "en": "AI Feature Requirements and Risk"
        },
        "slugs": [
          "ai-feature-testing"
        ]
      },
      {
        "key": "llm-与-prompt-评测设计",
        "title": {
          "zh-cn": "LLM 与 Prompt 评测设计",
          "en": "LLM and Prompt Evaluation Design"
        },
        "slugs": [
          "llm-evaluation-design",
          "llm-testing",
          "prompt-testing"
        ]
      },
      {
        "key": "agent-工具与安全测试",
        "title": {
          "zh-cn": "Agent、工具与安全测试",
          "en": "Agent, Tool, and Safety Testing"
        },
        "slugs": [
          "ai-agent-testing",
          "agent-tool-testing",
          "prompt-injection-testing"
        ]
      }
    ]
  },
  {
    "key": "skill-engineering-横向治理",
    "title": {
      "zh-cn": "Skill Engineering（横向治理）",
      "en": "Skill Engineering (cross-cutting governance)"
    },
    "slugs": [
      "skill-change-verification",
      "skill-prose-review",
      "skill-prose-trim"
    ],
    "groups": []
  }
];
